on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: macOS-latest
    steps:
    - name: deploy
      run: |
        echo $HOME
        echo $GITHUB_REPOSITORY
        ls $GITHUB_REPOSITORY
        # rm -rf docs
        # mkdir docs/
        # cp README.md docs/